/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColumnList: typeof import('./src/components/ColumnList.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/DropdownItem.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoginAndSign: typeof import('./src/components/LoginAndSign.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalLogin: typeof import('./src/components/ModalLogin.vue')['default']
    ModalSignup: typeof import('./src/components/ModalSignup.vue')['default']
    ModalTest: typeof import('./src/components/ModalTest.vue')['default']
    ModalTest1: typeof import('./src/components/ModalTest1.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    ValidateForm: typeof import('./src/components/ValidateForm.vue')['default']
    ValidateInput: typeof import('./src/components/ValidateInput.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
